In [18]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[:2,:3])
print("\n")
print(arr[:3,0:3:1])
print("\n")
print(arr[::-1,::-1])
print("\n")
print(arr[:,0])
print("\n")
print(arr[0,:])
print("\n")
print(arr[0])
print("\n")
print(arr)

[[1 2 3]
 [5 6 7]]


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


[1 5 9]


[1 2 3 4]


[1 2 3 4]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
