In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,1])

2


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,-1])

8


In [9]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [10]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5])
for x in  arr:
    print(x)

1
2
3
4
5


In [15]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[5,4,3,2,1]])
arr2=np.array([[6,7,8,9,10],[10,9,8,7,6]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 5  4  3  2  1 10  9  8  7  6]]


In [20]:
import numpy as np
arr=np.array([6,5,1,3,4,2])
arr1=np.sort(arr)
print(arr1)

[1 2 3 4 5 6]


In [25]:
from numpy import random
x=random.randint(100)
print(x)

41


In [32]:
from numpy import random
x=random.rand()
print(x)

0.3553166056750836


In [29]:
from numpy import random
x=random.rand(3,5)
print(x)

[[0.8094162  0.34718521 0.39834531 0.81717571 0.85505111]
 [0.67935927 0.29999088 0.70243445 0.7163271  0.79273385]
 [0.88501113 0.35542647 0.80558321 0.96285999 0.96916594]]


In [30]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[13 45 22 56 17]
 [86 30 52 71 31]
 [32 83 40 79 34]]


In [31]:
from numpy import random
x=random.rand(5)
print(x)

[0.46985176 0.74184621 0.75004898 0.29282329 0.44561004]


In [34]:
from numpy import random
x=random.randint(5)
print(x)

4


In [37]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(4,3)
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
from numpy import random
x=random.rand()
print(x)

0.14464346940816108
